# Use your own widget! 🎉
# This is ironic and perfect - a donation widget using itself for funding

custom:
  - "https://yourdomain.com/donate"
  # TODO: Replace with actual URL where CryptoMeACoffee widget is deployed
  # Example: https://lazaronacif.github.io/cryptomeacoffee-demo

# Optional: Add other funding platforms
# github: [LazaroNacif]
# patreon: username
# ko_fi: username
# buy_me_a_coffee: username
